using AmeisenBotX.Wow.Objects.Raw.SubStructs;
using System.Runtime.InteropServices;

namespace AmeisenBotX.Wow548.Objects.Descriptors
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WowPlayerDescriptor548
    {
        public ulong DuelArbiter;
        public int PlayerFlags;
        public int GuildRankId;
        public int GuildDeleteDate;
        public int GuildLevel;
        public int HairColorId;
        public int RestState;
        public int ArenaFaction;
        public int DuelTeam;
        public int GuildTimeStamp;
        public QuestlogEntry QuestlogEntry1;
        public QuestlogEntry QuestlogEntry2;
        public QuestlogEntry QuestlogEntry3;
        public QuestlogEntry QuestlogEntry4;
        public QuestlogEntry QuestlogEntry5;
        public QuestlogEntry QuestlogEntry6;
        public QuestlogEntry QuestlogEntry7;
        public QuestlogEntry QuestlogEntry8;
        public QuestlogEntry QuestlogEntry9;
        public QuestlogEntry QuestlogEntry10;
        public QuestlogEntry QuestlogEntry11;
        public QuestlogEntry QuestlogEntry12;
        public QuestlogEntry QuestlogEntry13;
        public QuestlogEntry QuestlogEntry14;
        public QuestlogEntry QuestlogEntry15;
        public QuestlogEntry QuestlogEntry16;
        public QuestlogEntry QuestlogEntry17;
        public QuestlogEntry QuestlogEntry18;
        public QuestlogEntry QuestlogEntry19;
        public QuestlogEntry QuestlogEntry20;
        public QuestlogEntry QuestlogEntry21;
        public QuestlogEntry QuestlogEntry22;
        public QuestlogEntry QuestlogEntry23;
        public QuestlogEntry QuestlogEntry24;
        public QuestlogEntry QuestlogEntry25;
        public VisibleItemEnchantment VisibleItemEnchantment1;
        public VisibleItemEnchantment VisibleItemEnchantment2;
        public VisibleItemEnchantment VisibleItemEnchantment3;
        public VisibleItemEnchantment VisibleItemEnchantment4;
        public VisibleItemEnchantment VisibleItemEnchantment5;
        public VisibleItemEnchantment VisibleItemEnchantment6;
        public VisibleItemEnchantment VisibleItemEnchantment7;
        public VisibleItemEnchantment VisibleItemEnchantment8;
        public VisibleItemEnchantment VisibleItemEnchantment9;
        public VisibleItemEnchantment VisibleItemEnchantment10;
        public VisibleItemEnchantment VisibleItemEnchantment11;
        public VisibleItemEnchantment VisibleItemEnchantment12;
        public VisibleItemEnchantment VisibleItemEnchantment13;
        public VisibleItemEnchantment VisibleItemEnchantment14;
        public VisibleItemEnchantment VisibleItemEnchantment15;
        public VisibleItemEnchantment VisibleItemEnchantment16;
        public VisibleItemEnchantment VisibleItemEnchantment17;
        public VisibleItemEnchantment VisibleItemEnchantment18;
        public VisibleItemEnchantment VisibleItemEnchantment19;
        public int PlayerTitle;
        public int FakeInebriation;
        public int VirtualPlayerRealm;
        public int CurrentSpecId;
        public int TaxiMountAnimKitId;
        public int CurrentBattlePetBreedQuality;
        public fixed int InvSlots[46];
        public fixed int PackSlots[32];
        public fixed int BankSlots[56];
        public fixed int VendorbuybackSlots[24];
        public ulong FarsightObject;
        public fixed int KnownTitles[10];
        public ulong Coinage;
        public int Xp;
        public int NextLevelXp;
        public fixed int Skill[448];
        public fixed int SkillLineids[64];
        public fixed int SkillSteps[64];
        public fixed int SkillRanks[64];
        public fixed int SkillStartingRanks[64];
        public fixed int SkillMaxRanks[64];
        public fixed int SkillModifiers[64];
        public fixed int SkillTalents[64];
        public int CharacterPoints;
        public int MaxTalentTiers;
        public int TrackCreatureMask;
        public int TrackResourceMask;
        public int MainhandExpertise;
        public int OffhandExpertise;
        public int RangedExpertise;
        public int CombatRatingExpertise;
        public int BlockPercentage;
        public int DodgePercentage;
        public int ParryPercentage;
        public int CritPercentage;
        public int RangedCritPercentage;
        public int OffhandCritPercentage;
        public fixed int SpellCritPercentage[7];
        public int ShieldBlock;
        public int ShieldBlockCritPercentage;
        public int Mastery;
        public int PvpPowerDamage;
        public int PvpPowerHealing;
        public fixed int ExploredZones[200];
        public int RestStateBonusPool;
        public fixed int ModDamageDonePos[7];
        public fixed int ModDamageDoneNeg[7];
        public fixed int ModDamageDonePercent[7];
        public int ModHealingDonePos;
        public int ModHealingPercent;
        public int ModHealingDonePercent;
        public int ModPeriodicHealingDonePercent;
        public fixed int WeaponDmgMultipliers[3];
        public int ModSpellPowerPercent;
        public int ModResiliencePercent;
        public int OverrideSpellPowerByAppercent;
        public int OverrideApbySpellPowerPercent;
        public int ModTargetResistance;
        public int ModTargetPhysicalResistance;
        public int LifetimeMaxRank;
        public int SelfResSpell;
        public int PvpMedals;
        public fixed int BuybackPrice[12];
        public fixed int BuybackTimestamp[12];
        public int YesterdayHonorableKills;
        public int LifetimeHonorableKills;
        public int WatchedFactionIndex;
        public fixed int CombatRatings[27];
        public fixed int PvpInfo[24];
        public int MaxLevel;
        public fixed int RuneRegen[4];
        public fixed int NoReagentCostMask[4];
        public fixed int GlyphSlots[6];
        public fixed int Glyphs[6];
        public int GlyphSlotsEnabled;
        public int PetSpellPower;
        public fixed int Researching[8];
        public ulong ProfessionSkillLine;
        public int UiHitModifier;
        public int UiSpellHitModifier;
        public int HomeRealmTimeOffset;
        public int ModPetHaste;
        public ulong SummonedBattlePetGuid;
        public int OverrideSpellsId;
        public int LfgBonusFactionId;
        public int LootSpecId;
        public int OverrideZonePvptype;
        public int ItemLevelDelta;
    }
}